-- 0034_digests.sql — stored weekly digests (hot leads, Tier-1, inbound to triage, data quality,
-- guardrail eval health). Generated by /api/cron/digest, viewable at /digest, optionally pushed to a
-- Slack-style webhook.

create table if not exists public.digests (
  id          uuid primary key default gen_random_uuid(),
  payload     jsonb not null default '{}'::jsonb,
  text        text,
  created_at  timestamptz not null default now()
);
create index if not exists digests_created_idx on public.digests(created_at desc);

alter table public.digests enable row level security;
drop policy if exists "digests_sel" on public.digests;
create policy "digests_sel" on public.digests for select to authenticated using (true);
